version: '3'

# Define the dev container with nvidia docker with dockerfile
services:
  dev:
    tty: true
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    ports:
      - 14008:8888
      - 14006:6006
      - 14007:15005
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0',]
            capabilities: [gpu]
    shm_size: 4gb
    # start jupyer lab with the following command : port 8888
    command: jupyter lab --ip=0.0.0.0 --port 8888 --allow-root --no-browser --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*' && \
        tensorboard --logdir /workspace/tensorboard --ip=0.0.0.0 --port 6006 --bind_all --host 0.0.0.0 && \
        mlflow ui --port 15005 --host 0.0.0.0 --file-store /workspace/mlruns