version: '3'

# Define the dev container with nvidia docker with dockerfile
services:
  dev:
    tty: true
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    ports:
      - 14008:8888
      - 14006:6006
      - 14007:15005
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0',]
            capabilities: [gpu]
    shm_size: 4gb
    # start jupyer lab with the following command : port 8888
    command: poetry run tensorboard --logdir /workspace/tensorboard --port 6006 --bind_all